# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: dotnet build $(buildConfiguration)
- script: dotnet tool install --global coverlet.console
- script: dotnet tool install dotnet-reportgenerator-globaltool --tool-path . --version 4.0.0-rc4
- script: dotnet test --configuration $(buildConfiguration) --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
  displayName: 'Unit testing'
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
- task: PublishCodeCoverageResults@1
  inputs:
    summaryFileLocation: $(Build.SourcesDirectory)\coverage.cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)
    codecoverageTool: cobertura
